import { useState, useEffect } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';

import Container from '@mui/material/Container';

import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

export default function Home() {
  // since we are on the same server
  // I don't need to put the domain.
  const RANDOM_QUOTE_URL = '/api/randomQuote'

  const [quoteData, setQuoteData] = useState({
    quote: "Quote here.",
    author: "Author here"
  })

  // write the click function
  // make it async
  // I want to fetch the data from the random quote url
  // I want to use an effect to load it when the page
  // is initially mounted


  const handleClick = async () => {
    try {
      // first we fetch
      const response = await fetch(RANDOM_QUOTE_URL,{
        method: "GET"
      })
      if (!response.ok) {
        throw new Error("Network error")
      }
      const data = await response.json()
      // then we set the data
      setQuoteData({
        quote: data.quote,
        author: data.author
      })

      console.log(data)
    } catch (error) {
      // handle this in a second
      console.error(error)
    }
  }

  useEffect(() => {
    console.log("On mount")
    // this is an async function called synchronously
    handleClick()
    // this is fine because we're not using the result
    // the function is executing and setting state
  }, [])
  // reminder [] for the dep array and the normal function will

  return (
    <div>
      <Head>
        <title>We Love Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            We Love Quotes
          </Typography>
        </Toolbar>
      </AppBar>
      <main>
        <Container maxWidth="sm">
          <Box
            sx={{
              bgcolor: 'background.paper',
              pt: 8,
              pb: 6,
            }}
          >
            <Typography variant="h5" align="center" color="text.primary" paragraph>
              {quoteData.quote}
            </Typography>
            <Typography
              component="h1"
              variant="h4"
              align="center"
              color="text.secondary"
              gutterBottom
            >
              {quoteData.author}
            </Typography>
            <Box
             display="flex"
             justifyContent="center"

            >
              <Button
                variant="contained"
                onClick={handleClick}
              >
                Get New Quote
              </Button>
            </Box>
          </Box>
        </Container>
      </main>
    </div>
  )
}
